# Generated by Django 5.1.4 on 2024-12-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="ai_response",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
    ]
