# Generated by Django 5.1.4 on 2024-12-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_messages", "0002_message_ai_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="user_id",
            field=models.CharField(default="123", max_length=20),
            preserve_default=False,
        ),
    ]
